# Generated by Django 3.1.3 on 2020-11-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is a test field '),
            preserve_default=False,
        ),
    ]
