# Generated by Django 3.1.2 on 2020-11-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20201123_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default=3, max_length=20),
            preserve_default=False,
        ),
    ]
